changelings = {
    "Beast": {
            "Broadback" : "",
            "Chimera" : "",
            "Cleareyes" : "",
            "Coldscale" : "",
            "Coyote" : "",
            "Nix" : "",
            "Hunterheart" : "",
            "Riddleseeker" : "",
            "Roteater" : "",
            "Runnerswift" : "",
            "Skitterskulk" : "",
            "Steepscrambler" : "",
            "Swimmerskin" : "",
            "Truefriend" : "",
            "Venombite" : "",
            "Windwing" : "",
            "Crypticskin(hb)" : "",
            "Hardshell(hb)" : "",
            "Hedgeurchin(hb)" : "",
            "Hiveborn(hb)" : "",
            "Qilin(hb)" : ""
        },

    "Darkling":
        {
            "Antiquarian" : "",
            "Gravewight" : "",
            "Illes" : "",
            "Leechfinger" : "",
            "Lurker" : "",
            "Lurkglider" : "",
            "Mirrorskin" : "",
            "Moonborn" : "",
            "Nightsinger" : "",
            "Palewraith" : "",
            "Pischacha" : "",
            "Razorhand" : "",
            "Skogsra" : "",
            "Tunnelgrub" : "",
            "Whisperwisp" : "",
            "Bogeyman(hb)" : "",
            "Engaoler(hb)" : "",
            "Frostfiend(hb)" : "",
            "Hushwight(hb)" : "",
            "Murkglow(hb)" : "",
            "Panopticon(hb)" : "",
            "Sporekin(hb)" : ""
        },

    "Elemental": 
        {
            "Airtouched" : "",
            "Apsaras" : "",
            "Ask-wee-da-eed" : "",
            "Blightbent" : "",
            "Earthbones" : "",
            "Di-cang" : "",
            "Fireheart" : "",
            "Levinquick" : "",
            "Manikin" : "",
            "Metalflesh" : "",
            "Sandharrowed" : "",
            "Snowskin" : "",
            "Waterborn" : "",
            "Woodblood" : "",
            "Acidvein(hb)" : "",
            "Clayshapen(hb)" : "",
            "Crystalsoul(hb)" : "",
            "Delicacy(hb)" : "",
            "Lusterlit(hb)" : "",
            "Magmasteeped(hb)" : "",
            "Newtonian(hb)" : "",
            "Shroudwrapped(hb)" : "",
            "Wirestreaked(hb)" : ""
        },

    "Fairest": 
        {
            "Bright One" : "",
            "Dancer" : "",
            "Draconic" : "",
            "Flamesiren" : "",
            "Flowering" : "",
            "Gandharva" : "",
            "Concubus" : "",
            "Muse" : "",
            "Playmate" : "",
            "Polychromatic" : "",
            "Shadowsoul" : "",
            "Telluric" : "",
            "Treasured" : "",
            "Weisse Frau" : "",
            "Apollonian(hb)" : "",
            "Courtesan(hb)" : "",
            "Dionysian(hb)" : "",
            "Gladiator(hb)" : "",
            "Gorgon(hb)" : "",
            "Lionhearted(hb)" : "",
            "Masterpiece(hb)" : "",
            "Pampered(hb)" : "",
        },

    "Ogre": 
        {
            "Bloodbrute" : "",
            "Coegrinder" : "",
            "Cyclopean" : "",
            "Daitya" : "",
            "Farwalker" : "",
            "Gargantuan" : "",
            "Gristlegrinder" : "",
            "Oni" : "",
            "Render" : "",
            "Stonebones" : "",
            "Troll" : "",
            "Water-dweller" : "",
            "Witchtooth" : "",
            "Bellower(hb)" : "",
            "Berserker(hb)" : "",
            "Bloodsoaker(hb)" : "",
            "Sentinel(hb)" : "",
        },

    "Wizened": 
        {
            "Artist" : "",
            "Author" : "",
            "Brewer" : "",
            "Chatelaine" : "",
            "Chirurgeon" : "",
            "Drudge" : "",
            "Fatemaker" : "",
            "Gameplayer" : "",
            "Gremlin" : "",
            "Pamarindo" : "",
            "Thusser" : "",
            "Inventor" : "",
            "Miner" : "",
            "Oracle" : "",
            "Smith" : "",
            "Soldier" : "",
            "Woodwalker" : "",
            "Barrister(hb)" : "",
            "Chaffeur(hb)" : "",
            "Gourmand(hb)" : "",
            "Huckster(hb)" : "",
            "Jester(hb)" : "",
            "Scrounger(hb)" : ""
        },

};